- hosts: all
  become : FALSE
  
  tasks:
  
 # Print a simple message.
    - local_action: 
        module: shell
        cmd: echo "Hello world!"
      ignore_errors: Yes
      register: StdOut
      when: "{{ansible_check_mode != ''}}"
      

